import requests
base='http://127.0.0.1:5000'
s = requests.Session()
print('Setting role -> owner')
s.get(base + '/set-role/owner')
print('Registering owner')
resp = s.post(base + '/api/register', json={'name':'Test Owner','email':'owner@example.com','password':'pass123'})
print('register:', resp.status_code, resp.text)
print('Logging in')
resp = s.post(base + '/api/login', json={'email':'owner@example.com','password':'pass123'})
print('login:', resp.status_code, resp.text)
print('Access owner page')
r = s.get(base + '/owner')
print('owner page status:', r.status_code)
print('Create a lot')
resp = s.post(base + '/api/lot', json={'location':'Meenakshi Mall','total_spots':10,'large_spots':3,'small_spots':6,'latitude':12.9716,'longitude':77.5946})
print('create lot:', resp.status_code, resp.text)
print('Get lots (should be empty for anon or show for owner)')
r = s.get(base + '/api/lots')
print('lots:', r.status_code, r.text)
